services:
  qdrant-ufro.esp3.local:
    container_name: qdrant-ufro.esp3.local
    hostname: drant-ufro.esp3.local 
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage 
    networks:
      - esp3_network

  assistant-ufro.esp3.local:
    container_name: assistant-ufro.esp3.local
    hostname: assistant-ufro.esp3.local
    build:
      context: .
      dockerfile: build/Dockerfile
    depends_on:
      - qdrant-ufro.esp3.local
    ports:
      - "33209:33209"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - esp3_network
  
volumes:
  qdrant_storage:
    driver: local
  

networks:
  esp3_network:
    external: true
      
